#!/bin/sh

set -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_input low lswpentaho/domain || true
db_input low lswpentaho/port || true
db_input low lswpentaho/mysqlroot || true
db_input low lswpentaho/mysql-pentaho-user || true
db_input low lswpentaho/mysql-pentaho-password || true
db_input low lswpentaho/adminconsole-username || true
db_input low lswpentaho/adminconsole-password || true
db_input low lswpentaho/adminconsole-platform-username || true
db_input low lswpentaho/publish-password || true

# Show interface
db_go || true
